sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '6'
  - '7'
  - '8'

before_script:
  - npm prune

after_success:
  - npm install coveralls@^2.11.9 && cat ./coverage/lcov.info | coveralls

before_deploy:
  - npm install
  - npm run build

deploy:
  provider: script
  script: npm run semantic-release
  on:
    branch: master
